name: Release Workflow

on: [push]
# on:
#     push:
#       branches:
#         - master

jobs:
    build:
        name: Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            - name: Setup Spigot NMS action
              uses: derongan/nmsaction@v1
              with:
                rev: 1.16.1

            - name: Install Spigot NMS
              run: mkdir -p $HOME/.m2/repository && cp -a nms-build/.m2/repository/. $HOME/.m2/repository

            - name: Build with Maven
              run: mvn package --file pom.xml
